// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMsJBo4A7hdbRuyFnkzmJmVFgHhhD2Yss',
    appId: '1:2534414693:web:979c55e2356d55ce32e98c',
    messagingSenderId: '2534414693',
    projectId: 'carrot-e989f',
    authDomain: 'carrot-e989f.firebaseapp.com',
    storageBucket: 'carrot-e989f.appspot.com',
    measurementId: 'G-C7W3S9E62G',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMsJBo4A7hdbRuyFnkzmJmVFgHhhD2Yss',
    appId: '1:2534414693:web:549a6f529d93382d32e98c',
    messagingSenderId: '2534414693',
    projectId: 'carrot-e989f',
    authDomain: 'carrot-e989f.firebaseapp.com',
    storageBucket: 'carrot-e989f.appspot.com',
    measurementId: 'G-FDNNGPYTN8',
  );
}
